### ISSUE TITLE
Addition of Glen Lifecycle page

### ISSUE THREAD

**Issue by tkinnison** [RainyDayMedia/theglen#16]
We will need to add the customer lifecycle infographic to its own page. I will be sending a .svg for that and it can sit over top of the polka dotted background. Not going to place it inside it's own background like the services model above. The 5 lists describing the lifecycle flow can be 3 columns and adjust down to one column at mobile view if needed. Will let you know when the image is ready to pull down from Dropbox.

**Comment by tkinnison** [comment]
GSJ_Lifecycle_NEW_v1.psd mock up has been uploaded to dropbox file.

Client said that this lifecycle graphic could exist outside of the About Page and doesn't need to be included in the main navigation or main menu (because it's not really supposed to be an external facing doc). Let's create a separate page for it and add a button link next to ELC link at the top of the About Page that says Glen Lifecycle.

Include on the new page a text field option (left copy) below the title in case they want to add a short paragraph about the graphic being shown below. Let me know if you need any additional direction.

**Comment by Toddses** [comment]
done.
